# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0002_remove_casa_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='description',
            field=models.TextField(default=213),
            preserve_default=False,
        ),
    ]
