# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0006_auto_20161014_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=600)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobili.Casa')),
            ],
        ),
    ]
