# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation', models.CharField(choices=[('0', 'Venta'), ('1', 'Alquiler')], default='0', max_length=6)),
                ('location', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('surface', models.CharField(max_length=60)),
                ('free_surface', models.CharField(max_length=60)),
                ('cover_surface', models.CharField(max_length=60)),
                ('rooms', models.CharField(max_length=60)),
                ('bathrooms', models.CharField(max_length=60)),
                ('condition', models.CharField(max_length=60)),
                ('heating', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
    ]
