# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='img_frente',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='casa',
            name='price',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
