# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0005_auto_20161007_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(default='', max_length=256),
        ),
    ]
