# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 19:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0008_auto_20161014_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/home/rodri/Cole/Programacion3/ProyectoFinal/inmobiliaria/media/casa-images/'))),
            ],
        ),
        migrations.AddField(
            model_name='casa',
            name='tipo',
            field=models.CharField(choices=[(0, 'Departamento'), (1, 'Casa'), (2, 'Oficina')], default=1, max_length=16),
        ),
        migrations.AlterField(
            model_name='casa',
            name='Operation',
            field=models.CharField(choices=[(0, 'Venta'), (1, 'Alquiler')], default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='casa',
            name='img_frente',
            field=models.ImageField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/home/rodri/Cole/Programacion3/ProyectoFinal/inmobiliaria/media/casa-images/')),
        ),
        migrations.AlterField(
            model_name='comment',
            name='casa',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='inmobili.Casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='casa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmobili.Casa'),
        ),
    ]
