# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0009_auto_20161017_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='people',
            field=models.CharField(default=5, max_length=60),
            preserve_default=False,
        ),
    ]
