# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0010_casa_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='Operation',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='casa',
            name='tipo',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Oficina', 'Oficina')], default=1, max_length=16),
        ),
    ]
