# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0012_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='author',
            field=models.CharField(max_length=60),
        ),
    ]
