# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0015_auto_20161023_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='casa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inmobili.Casa'),
            preserve_default=False,
        ),
    ]
