# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 12:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0016_auto_20161023_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='satifaccion',
        ),
        migrations.AlterField(
            model_name='casa',
            name='img_frente',
            field=models.ImageField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/home/rodri/Cole/Programacion3/proyecto final/inmobiliaria/media/casa-images/')),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/home/rodri/Cole/Programacion3/proyecto final/inmobiliaria/media/casa-images/')),
        ),
    ]
