# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0017_auto_20161024_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
