# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0018_auto_20161024_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='img_frente',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
