# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0023_auto_20161027_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='img_frente',
            field=models.ImageField(upload_to='casa/', verbose_name='Imagen de la Casa'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='casa/', verbose_name='Imagen de la Casa'),
        ),
    ]
