# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0026_auto_20161107_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='address',
            field=models.CharField(max_length=60, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Ba\xf1os'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='condition',
            field=models.CharField(max_length=60, verbose_name='Condicion'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='cover_surface',
            field=models.CharField(max_length=60, verbose_name='Superficie cubierta'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='district',
            field=models.CharField(max_length=60, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='free_surface',
            field=models.CharField(max_length=60, verbose_name='Superficie Libre'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='heating',
            field=models.CharField(max_length=60, verbose_name='Calefaccion'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='location',
            field=models.CharField(max_length=60, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='people',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Personas'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='rooms',
            field=models.IntegerField(default=1, verbose_name='Ambientes'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='surface',
            field=models.CharField(max_length=60, verbose_name='Superficie'),
        ),
    ]
