# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0027_auto_20161111_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobili.Casa'),
        ),
    ]
