# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobili', '0029_casa_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=600)),
                ('casa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobili.Casa')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobili.Comment')),
            ],
        ),
    ]
